name: Deploy Two .NET Projects to Azure

on:
  push:
    branches:
      - main  # uruchamiaj pipeline po puszu na branch main
  workflow_dispatch:  # opcja manualnego uruchamiania z GitHub UI
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
    DriveIt:
      name: Build and deploy DriveIt
      uses: ./.github/workflows/main_driveit.yml
      
    DriveItAPI:
      name: Build and deploy DriveItAPI
      uses: ./.github/workflows/main_driveitapi.yml
